### ISSUE TITLE
Feedback on week 13 project progress for CS2113-T16-2

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T16-2/main#183]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-13] (:exclamation:)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @nimiew for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T16-2/main/issues/169 https://github.com/AY1920S1-CS2113-T16-2/main/issues/166 https://github.com/AY1920S1-CS2113-T16-2/main/issues/144 https://github.com/AY1920S1-CS2113-T16-2/main/issues/143 https://github.com/AY1920S1-CS2113-T16-2/main/issues/99 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @nicholasnovakovic for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T16-2/main/pull/180 https://github.com/AY1920S1-CS2113-T16-2/main/issues/169 https://github.com/AY1920S1-CS2113-T16-2/main/issues/166 https://github.com/AY1920S1-CS2113-T16-2/main/issues/157 https://github.com/AY1920S1-CS2113-T16-2/main/issues/154 https://github.com/AY1920S1-CS2113-T16-2/main/issues/152 https://github.com/AY1920S1-CS2113-T16-2/main/issues/148 https://github.com/AY1920S1-CS2113-T16-2/main/issues/146 https://github.com/AY1920S1-CS2113-T16-2/main/issues/140 https://github.com/AY1920S1-CS2113-T16-2/main/issues/120 https://github.com/AY1920S1-CS2113-T16-2/main/issues/103 https://github.com/AY1920S1-CS2113-T16-2/main/issues/102 https://github.com/AY1920S1-CS2113-T16-2/main/issues/100 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @shaun97 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T16-2/main/pull/181 https://github.com/AY1920S1-CS2113-T16-2/main/pull/165 https://github.com/AY1920S1-CS2113-T16-2/main/issues/170 https://github.com/AY1920S1-CS2113-T16-2/main/issues/169 https://github.com/AY1920S1-CS2113-T16-2/main/issues/166 https://github.com/AY1920S1-CS2113-T16-2/main/issues/160 https://github.com/AY1920S1-CS2113-T16-2/main/issues/155 https://github.com/AY1920S1-CS2113-T16-2/main/issues/153 https://github.com/AY1920S1-CS2113-T16-2/main/issues/151 https://github.com/AY1920S1-CS2113-T16-2/main/issues/147 https://github.com/AY1920S1-CS2113-T16-2/main/issues/145 https://github.com/AY1920S1-CS2113-T16-2/main/issues/142 https://github.com/AY1920S1-CS2113-T16-2/main/issues/141 https://github.com/AY1920S1-CS2113-T16-2/main/issues/139 https://github.com/AY1920S1-CS2113-T16-2/main/issues/138 https://github.com/AY1920S1-CS2113-T16-2/main/issues/137 https://github.com/AY1920S1-CS2113-T16-2/main/issues/136 https://github.com/AY1920S1-CS2113-T16-2/main/issues/135 https://github.com/AY1920S1-CS2113-T16-2/main/issues/134 https://github.com/AY1920S1-CS2113-T16-2/main/issues/133 https://github.com/AY1920S1-CS2113-T16-2/main/issues/131 https://github.com/AY1920S1-CS2113-T16-2/main/issues/129 https://github.com/AY1920S1-CS2113-T16-2/main/issues/127 https://github.com/AY1920S1-CS2113-T16-2/main/issues/126 https://github.com/AY1920S1-CS2113-T16-2/main/issues/125 https://github.com/AY1920S1-CS2113-T16-2/main/issues/124 https://github.com/AY1920S1-CS2113-T16-2/main/issues/123 https://github.com/AY1920S1-CS2113-T16-2/main/issues/121 https://github.com/AY1920S1-CS2113-T16-2/main/issues/120 https://github.com/AY1920S1-CS2113-T16-2/main/issues/119 https://github.com/AY1920S1-CS2113-T16-2/main/issues/117 https://github.com/AY1920S1-CS2113-T16-2/main/issues/106 https://github.com/AY1920S1-CS2113-T16-2/main/issues/65 https://github.com/AY1920S1-CS2113-T16-2/main/issues/64 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @sanjukta99

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-14 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
